services:
  mlflow:
    image: python:3.11-slim
    working_dir: /app
    environment:
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI:-sqlite:////mlflow/mlflow.db}
      MLFLOW_ARTIFACT_ROOT: ${MLFLOW_ARTIFACT_ROOT:-/mlflow/artifacts}
    command: >
      bash -c "pip install mlflow &&
                mlflow server --host 0.0.0.0 --port 5000 
                --backend-store-uri ${MLFLOW_BACKEND_STORE_URI:-sqlite:////mlflow/mlflow.db} 
                --default-artifact-root ${MLFLOW_ARTIFACT_ROOT:-/mlflow/artifacts}"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow


